# Set 04 – Vorverarbeitung mit scikit-learn

scikit-learn besteht nicht nur aus Modellen. Es bietet Transformer, die Daten nach festen Regeln vorbereiten. Hier werden die Bausteine ohne Klassifikation und ohne Vorhersage eingeführt.

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

## 1. Beispieldaten

Die Referenzdaten enthalten Zahlen, Kategorien und fehlende Werte. Die zweite Tabelle simuliert später eintreffende Daten. München kommt nur dort vor und ist eine unbekannte Kategorie.

In [2]:
referenz = pd.DataFrame({
    "alter": [24, 37, np.nan, 52, 46, 31],
    "einkommen": [3100, 4200, 3900, np.nan, 6100, 3600],
    "stadt": ["Berlin", "Köln", "Berlin", "Hamburg", np.nan, "Köln"],
})
neu = pd.DataFrame({
    "alter": [29, np.nan],
    "einkommen": [3500, 4700],
    "stadt": ["München", "Berlin"],
})
display(referenz)
display(neu)

   alter  einkommen    stadt
0   24.0     3100.0   Berlin
1   37.0     4200.0     Köln
2    NaN     3900.0   Berlin
3   52.0        NaN  Hamburg
4   46.0     6100.0      NaN
5   31.0     3600.0     Köln

   alter  einkommen    stadt
0   29.0       3500  München
1    NaN       4700   Berlin

## 2. Das Transformer-Prinzip

- fit(X) lernt benötigte Werte oder Kategorien aus X.
- transform(X) wendet die gelernten Regeln an.
- fit_transform(X) führt beides direkt nacheinander aus.

Neue Daten werden nur mit transform() verarbeitet. Sonst würden die Regeln verändert.

## 3. Fehlende Zahlen mit SimpleImputer

Der Imputer lernt für jede Zahlenspalte den Median. Das Attribut statistics_ zeigt die gelernten Ersatzwerte.

In [3]:
zahlen = referenz[["alter", "einkommen"]]
zahlen_imputer = SimpleImputer(strategy="median")
zahlen_aufbereitet = zahlen_imputer.fit_transform(zahlen)
print("Gelernte Medianwerte:", zahlen_imputer.statistics_)
display(pd.DataFrame(zahlen_aufbereitet, columns=zahlen.columns))

Gelernte Medianwerte: [  37. 3900.]

   alter  einkommen
0   24.0     3100.0
1   37.0     4200.0
2   37.0     3900.0
3   52.0     3900.0
4   46.0     6100.0
5   31.0     3600.0

## 4. Zahlen mit StandardScaler skalieren

Der Scaler lernt Mittelwerte und Standardabweichungen. Danach liegen die transformierten Spalten ungefähr um 0 und sind vergleichbar skaliert.

In [4]:
scaler = StandardScaler()
zahlen_skaliert = scaler.fit_transform(zahlen_aufbereitet)
print("Gelernte Mittelwerte:", scaler.mean_.round(2))
print("Gelernte Skalierungen:", scaler.scale_.round(2))
display(pd.DataFrame(zahlen_skaliert, columns=zahlen.columns).round(2))

Gelernte Mittelwerte: [  37.83 4133.33]
Gelernte Skalierungen: [  9.19 942.81]

   alter  einkommen
0  -1.51      -1.10
1  -0.09       0.07
2  -0.09      -0.25
3   1.54      -0.25
4   0.89       2.09
5  -0.74      -0.57

## 5. Fehlende Kategorien auffüllen

most_frequent ersetzt fehlende Werte durch die häufigste Ausprägung.

In [5]:
kategorie = referenz[["stadt"]]
kategorie_imputer = SimpleImputer(strategy="most_frequent")
kategorie_aufbereitet = kategorie_imputer.fit_transform(kategorie)
print("Häufigste Kategorie:", kategorie_imputer.statistics_)
display(pd.DataFrame(kategorie_aufbereitet, columns=["stadt"]))

Häufigste Kategorie: ['Berlin']

     stadt
0   Berlin
1     Köln
2   Berlin
3  Hamburg
4   Berlin
5     Köln

## 6. Kategorien mit OneHotEncoder codieren

Für jede bekannte Kategorie entsteht eine 0/1-Spalte. handle_unknown="ignore" verhindert einen Fehler bei unbekannten Kategorien.

In [6]:
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
stadt_codiert = encoder.fit_transform(kategorie_aufbereitet)
print("Gelernte Kategorien:", encoder.categories_)
display(pd.DataFrame(stadt_codiert, columns=encoder.get_feature_names_out(["stadt"])))

Gelernte Kategorien: [array(['Berlin', 'Hamburg', 'Köln'], dtype=object)]

   stadt_Berlin  stadt_Hamburg  stadt_Köln
0           1.0            0.0         0.0
1           0.0            0.0         1.0
2           1.0            0.0         0.0
3           0.0            1.0         0.0
4           1.0            0.0         0.0
5           0.0            0.0         1.0

## 7. Gelernte Regeln auf neue Daten anwenden

Für neu verwenden wir ausschließlich transform(). Medianwerte, Skalierung und Kategorien stammen weiterhin aus der Referenztabelle.

In [7]:
neu_zahlen = zahlen_imputer.transform(neu[["alter", "einkommen"]])
neu_zahlen = scaler.transform(neu_zahlen)
neu_stadt = kategorie_imputer.transform(neu[["stadt"]])
neu_stadt = encoder.transform(neu_stadt)

display(pd.DataFrame(neu_zahlen, columns=["alter", "einkommen"]).round(2))
display(pd.DataFrame(neu_stadt, columns=encoder.get_feature_names_out(["stadt"])))

   alter  einkommen
0  -0.96      -0.67
1  -0.09       0.60

   stadt_Berlin  stadt_Hamburg  stadt_Köln
0           0.0            0.0         0.0
1           1.0            0.0         0.0

## Zwischenfazit

Die Transformer funktionieren, aber Reihenfolge und Spalten wurden manuell verwaltet. Im nächsten Notebook bündeln Pipeline und ColumnTransformer diese Schritte reproduzierbar.